/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as erc20TokenSol from "./Erc20Token.sol";
import type * as src from "./src";
import type * as test from "./test";

export type { erc20TokenSol };

export type { src };

export type { test };
export type { ERC721Token } from "./ERC721Token";
