/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721Receiver } from "./IERC721Receiver";
export type { IERC721Token } from "./IERC721Token";
