/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export declare namespace IERC20Transformer {
  export type TransformContextStruct = {
    sender: string;
    recipient: string;
    data: BytesLike;
  };

  export type TransformContextStructOutput = [string, string, string] & {
    sender: string;
    recipient: string;
    data: string;
  };
}

export interface FillQuoteTransformerInterface extends utils.Interface {
  functions: {
    "bridgeAdapter()": FunctionFragment;
    "deployer()": FunctionFragment;
    "die(address)": FunctionFragment;
    "transform((address,address,bytes))": FunctionFragment;
    "zeroEx()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bridgeAdapter"
      | "deployer"
      | "die"
      | "transform"
      | "zeroEx"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bridgeAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(functionFragment: "die", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transform",
    values: [IERC20Transformer.TransformContextStruct]
  ): string;
  encodeFunctionData(functionFragment: "zeroEx", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "bridgeAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "die", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transform", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zeroEx", data: BytesLike): Result;

  events: {
    "ProtocolFeeUnfunded(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProtocolFeeUnfunded"): EventFragment;
}

export interface ProtocolFeeUnfundedEventObject {
  orderHash: string;
}
export type ProtocolFeeUnfundedEvent = TypedEvent<
  [string],
  ProtocolFeeUnfundedEventObject
>;

export type ProtocolFeeUnfundedEventFilter =
  TypedEventFilter<ProtocolFeeUnfundedEvent>;

export interface FillQuoteTransformer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FillQuoteTransformerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bridgeAdapter(overrides?: CallOverrides): Promise<[string]>;

    deployer(overrides?: CallOverrides): Promise<[string]>;

    die(
      ethRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transform(
      context: IERC20Transformer.TransformContextStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    zeroEx(overrides?: CallOverrides): Promise<[string]>;
  };

  bridgeAdapter(overrides?: CallOverrides): Promise<string>;

  deployer(overrides?: CallOverrides): Promise<string>;

  die(
    ethRecipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transform(
    context: IERC20Transformer.TransformContextStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  zeroEx(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    bridgeAdapter(overrides?: CallOverrides): Promise<string>;

    deployer(overrides?: CallOverrides): Promise<string>;

    die(ethRecipient: string, overrides?: CallOverrides): Promise<void>;

    transform(
      context: IERC20Transformer.TransformContextStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    zeroEx(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ProtocolFeeUnfunded(bytes32)"(
      orderHash?: null
    ): ProtocolFeeUnfundedEventFilter;
    ProtocolFeeUnfunded(orderHash?: null): ProtocolFeeUnfundedEventFilter;
  };

  estimateGas: {
    bridgeAdapter(overrides?: CallOverrides): Promise<BigNumber>;

    deployer(overrides?: CallOverrides): Promise<BigNumber>;

    die(
      ethRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transform(
      context: IERC20Transformer.TransformContextStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    zeroEx(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bridgeAdapter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    die(
      ethRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transform(
      context: IERC20Transformer.TransformContextStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    zeroEx(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
