/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as testMintableErc721TokenSol from "./TestMintableERC721Token.sol";
import type * as testMintableErc1155TokenSol from "./TestMintableERC1155Token.sol";

export type { testMintableErc1155TokenSol };

export type { testMintableErc721TokenSol };
export type { TestMintableERC20Token } from "./TestMintableERC20Token";
export type { TestTokenSpenderERC20Token } from "./TestTokenSpenderERC20Token";
export type { TestWeth } from "./TestWeth";
