/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuthorizableV06 } from "./IAuthorizableV06";
export type { IOwnableV06 } from "./IOwnableV06";
