/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IUniswapV3PoolDeployer,
  IUniswapV3PoolDeployerInterface,
} from "../../../../../contracts/test/integration/TestUniswapV3Pool.sol/IUniswapV3PoolDeployer";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "creationParameters",
    outputs: [
      {
        components: [
          {
            internalType: "contract IERC20TokenV06",
            name: "token0",
            type: "address",
          },
          {
            internalType: "contract IERC20TokenV06",
            name: "token1",
            type: "address",
          },
          {
            internalType: "uint24",
            name: "fee",
            type: "uint24",
          },
        ],
        internalType: "struct IUniswapV3PoolDeployer.CreationParameters",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUniswapV3PoolDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapV3PoolDeployerInterface {
    return new utils.Interface(_abi) as IUniswapV3PoolDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniswapV3PoolDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IUniswapV3PoolDeployer;
  }
}
