export const GET_MY_ACTIONS = "GET_MY_ACTIONS";
export const GET_MY_ACTIONS_SUCCESS = "GET_MY_ACTIONS_SUCCESS";
export const GET_MY_ACTIONS_FAIL = "GET_MY_ACTIONS_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
