/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export declare namespace IERC20Transformer {
  export type TransformContextStruct = {
    sender: string;
    recipient: string;
    data: BytesLike;
  };

  export type TransformContextStructOutput = [string, string, string] & {
    sender: string;
    recipient: string;
    data: string;
  };
}

export interface TestTransformerHostInterface extends utils.Interface {
  functions: {
    "rawExecuteTransform(address,(address,address,bytes))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "rawExecuteTransform"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "rawExecuteTransform",
    values: [string, IERC20Transformer.TransformContextStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "rawExecuteTransform",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TestTransformerHost extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestTransformerHostInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    rawExecuteTransform(
      transformer: string,
      context: IERC20Transformer.TransformContextStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  rawExecuteTransform(
    transformer: string,
    context: IERC20Transformer.TransformContextStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    rawExecuteTransform(
      transformer: string,
      context: IERC20Transformer.TransformContextStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    rawExecuteTransform(
      transformer: string,
      context: IERC20Transformer.TransformContextStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    rawExecuteTransform(
      transformer: string,
      context: IERC20Transformer.TransformContextStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
