/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface TestSimpleFunctionRegistryFeatureImpl2Interface
  extends utils.Interface {
  functions: {
    "testFn()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "testFn"): FunctionFragment;

  encodeFunctionData(functionFragment: "testFn", values?: undefined): string;

  decodeFunctionResult(functionFragment: "testFn", data: BytesLike): Result;

  events: {};
}

export interface TestSimpleFunctionRegistryFeatureImpl2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestSimpleFunctionRegistryFeatureImpl2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    testFn(overrides?: CallOverrides): Promise<[BigNumber] & { id: BigNumber }>;
  };

  testFn(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    testFn(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    testFn(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    testFn(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
